### ISSUE TITLE
Yocto Python3 installation needs additional packages/features

### ISSUE THREAD

**Issue by Horrendus** [Qinematiq/meta-imageplus#2]
* pip3 install twisted (needed for django-channels) has an error
* django doesn't work because python3 is missing sqlite3 module (even though it is in the python3 stdlib)
* opencv3 python3 bindings need to run on the system
* check splineinterpolator
* when calibrator is ported to python3, it needs to be tested in the OS

**Comment by fsasm** [comment]
I will try tomorrow with `CORE_IMAGE_EXTRA_INSTALL_append = " python3 python3-modules "`

**Comment by fsasm** [comment]
Some extra Python3 modules are installed but twisted still can't be installed via pip3, despite upgrading setuptools, pip and ez_install. Installation aborts with the error message `Command "python setup.py egg_info" failed with error code 1`.

splineinterpolator runs fine with the installed python3.

**Comment by Horrendus** [comment]
We abandoned django-channels & twisted for the first version, all other dependencies should be satisfied afaik
